blog/urls.py
from django.conf.urls import static
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='blog'

urlpatterns = [
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<seotitle>[\d\w\-]+)/$', views.blog_post, name='blog_post'), 
    url(r'^manage(?:/(?P<pk>[\d\w\-]+))?', views.manage, name='manage'),
    url('', views.home, name='home'),
]

portfolio/urls.py
from django.conf.urls import static
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='portfolio'

urlpatterns = [
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<seotitle>[\d\w\-]+)/$', views.portfolio_post, name='portfolio_post'), 
    url(r'^manage(?:/(?P<pk>[\d\w\-]+))?', views.manage, name='manage'),
    url('', views.home, name='home'),
]

portfolio/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta, datetime, date

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    seotitle = models.CharField(max_length=50,unique=True)
    pub_date = models.DateTimeField()
    image = models.ImageField(upload_to='portfolio/%Y/%m/%d/',null=True,blank=True)
    body = models.TextField()
    #date = models.IntegerField(null=True,blank=True)
    #intro = models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.title

    def pub_date_pretty(self):
       return self.pub_date.strftime('%b %e %Y')

    def summary(self):
        return self.body[:100]

    def url(self):
        datestuff = self.pub_date.strftime('%Y/%m/%d')
        return '{0}/{1}'.format(datestuff,self.seotitle)

    class Meta:
        unique_together = ("pub_date", "seotitle")

portfolio/forms.py
from django import forms
from .models import Post
from django.conf import settings

class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm,self).__init__(*args,**kwargs)
        for field_name, field in self.fields.items():
            if field_name is 'image':
                field.widget.attrs['class'] = 'form-inline'
            else:
                field.widget.attrs['class'] = 'form-control'
            if field_name == 'pub_date':
                field.input_formats = settings.DATE_INPUT_FORMATS # what if this isn't in settings?
            field.widget.attrs['placeholder'] = field.help_text

class PostForm(BaseForm):
    #def __init__(self, *args, **kwargs):
    #    super(PostForm, self).__init__(*args, **kwargs)
        #self.fields['intro'].required = False
        #self.fields['date'].required = False

    class Meta:
        model = Post
        fields = '__all__'
        #exclude = ['intro','date']
        widgets = {        
            'pub_date': forms.DateTimeInput(format='%d/%m/%Y')
        }
        labels = {
            'title':'info',
            'seotitle':'link',
            'pub_date':'calendar',
            'image':'picture-o',
            'body':'newspaper-o'
        }
        help_texts = {
            'title':'Title',
            'seotitle':'Part of the url: path/<seotitle here>',
            'pub_date':'Date of the event',
            'image':'Photo of the event',
            'body':'Main text'
        }

portfolio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
#from django.contrib.auth.models import User
from django.utils import timezone
from datetime import date, datetime, time, timedelta
from .models import Post
from .forms import PostForm
from django.conf import settings
import os

def home(request):
    posts = Post.objects.order_by('-pub_date')
    return render(request,'portfolio/home.html',{'posts':posts})

def portfolio_post(request,year,month,day,seotitle):
    pdate = date(int(year),int(month),int(day))
    daystart = timezone.make_aware(datetime.combine(pdate, time.min))
    dayend = timezone.make_aware(datetime.combine(pdate, time.max))
    post = get_object_or_404(Post, seotitle=seotitle,pub_date__range=(daystart,dayend))
    return render(request,'portfolio/portfolio_post.html',{'post':post})

@login_required
def manage(request,pk=''):
    if pk is not None and len(pk) > 0:
        post = get_object_or_404(Post,pk=pk) 
    else:
        post = Post()

    if request.method == 'POST':
        error = ''
        form = PostForm(request.POST,request.FILES,instance=post,label_suffix='')

        # DELETE THE POST       
        if 'deleterow' in request.POST:
            if form.image is not None:
                try:
                    os.remove(settings.BASE_DIR + os.path.normpath(post.image.url))
                except:
                    error = 'could not delete file'
            post.delete()
            return redirect('portfolio:home')

        # ADD/EDIT THE POST
        datestring = datetime.strptime(request.POST['pub_date'], '%d/%m/%Y')
        if form.is_valid():
            obj = form.save(commit=False)
            obj.pub_date = timezone.make_aware(datetime.combine(datestring, time.min))
            #obj.author = request.user
            obj.save()
            if 'save' in request.POST:
                return redirect('portfolio:home')
        else:
            error = 'Please fill in all fields.'
        return render(request,'portfolio/create.html',{'error':error,'form':form,'pk':pk})
    else:
        form = PostForm(instance=post,label_suffix='')
        return render(request,'portfolio/create.html',{'form':form,'pk':pk})

portfolio/templates/portfolio/create.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'portfolio/lib/bootstrap-datepicker-1.6.4-dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}
{% block content %}
<h1>{% if form.instance.id %}Edit{% else %}Create{% endif %} Post</h1>
{% if form.errors %}
<div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Error:<br>{{ form.errors }}</div>
{% endif %}
{% if form.instance.id %}
<form action="{% url 'portfolio:manage' form.instance.id %}" method="post" enctype="multipart/form-data">
{% else %}
<form action="{% url 'portfolio:manage' %}" method="post" enctype="multipart/form-data">
{% endif %}
{% csrf_token %}
{% for field in form %}
    {% if field.name == 'typ' %}
        <h4><i class="fa fa-{{ field.label }} fa-fw" aria-hidden="true"></i> {{ field.help_text }}</h4>
        <div class="form-inline">
        {% for choice in field %}
            <label class="custom-control custom-radio {{ choice.choice_label|lower }}">
                {{ choice.tag }}            
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">{{ choice.choice_label|safe }}</span>
            </label>
        {% endfor %}
        </div>
    {% else %}
        <div class="input-group">
            <label for="{{ field.auto_id }}" class="input-group-addon" title="{{ field.help_text }}"><i class="fa fa-{{ field.label }} fa-fw" aria-hidden="true"></i></label>
            {% if field.name == 'image' and form.image %}<span class="form-control" style="display:inline">{% endif %}
            {{ field }}
            {% if field.name == 'image' %}</span>{% endif %}
        </div>
    {% endif %}
<br>
{% endfor %}

<br><br>
<button class="btn btn-primary" type="submit" name="savecontinue"><i class="fa fa-floppy-o" aria-hidden="true"></i> {% if form.instance.id %}Save{% else %}Add{% endif %} and continue editing</button> <button class="btn btn-primary" type="submit" name="save"><i class="fa fa-floppy-o" aria-hidden="true"></i> {% if form.instance.id %}Save{% else %}Add{% endif %}</button>
{% if form.instance.id %}<button class="btn btn-danger" type="submit" name="deleterow"><i class="fa fa-times" aria-hidden="true"></i> Delete</button>
{% endif %}
</form>
{% endblock %}
{% block script %}
<script src="{% static 'portfolio/lib/bootstrap-datepicker-1.6.4-dist/js/bootstrap-datepicker.js' %}"></script>
<script src="https://cdn.ckeditor.com/4.7.1/full/ckeditor.js"></script>
<script>
$(document).ready(function(){
    $('#id_pub_date').datepicker({ 
    format: 'dd/mm/yyyy',
    orientation: 'bottom',
    todayHighlight: true
    });
});
// https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic
CKEDITOR.replace( 'id_body', {
    customConfig: '',
    toolbarGroups: [
        { name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
        { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
        { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
        { name: 'forms', groups: [ 'forms' ] },
        { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
        { name: 'links', groups: [ 'links' ] },
        '/',
        { name: 'styles', groups: [ 'styles' ] },
        { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
        { name: 'insert', groups: [ 'insert' ] },
        { name: 'colors', groups: [ 'colors' ] },
        { name: 'tools', groups: [ 'tools' ] },
        { name: 'others', groups: [ 'others' ] },

        { name: 'about', groups: [ 'about' ] }
    ],
    removeButtons: 'Save,NewPage,Preview,Print,Templates,SelectAll,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,CopyFormatting,RemoveFormat,Language,BidiRtl,BidiLtr,Flash,PageBreak,Iframe,Font,FontSize,About'
});
/*
CKEDITOR.editorConfig = function( config ) {
    config.toolbarGroups = [
        { name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
        { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
        { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
        { name: 'forms', groups: [ 'forms' ] },
        { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
        { name: 'links', groups: [ 'links' ] },
        '/',
        { name: 'styles', groups: [ 'styles' ] },
        { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
        { name: 'insert', groups: [ 'insert' ] },
        { name: 'colors', groups: [ 'colors' ] },
        { name: 'tools', groups: [ 'tools' ] },
        { name: 'others', groups: [ 'others' ] },
        { name: 'about', groups: [ 'about' ] }
    ];

    config.removeButtons = 'Save,NewPage,Preview,Print,Templates,SelectAll,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,CopyFormatting,RemoveFormat,Language,BidiRtl,BidiLtr,Flash,PageBreak,Iframe,Font,FontSize,About';
};
*/
$('#id_seotitle').on("keyup",function(){seoInput($(this))});

$('#id_seotitle').on("focus",function(){
    if($(this).val().length < 1){
        $(this).val=$('#id_title').val().toLowerCase();
        $(this).val(function(i, v) {return $('#id_title').val().toLowerCase();});
        seoInput($(this))
    }
});
function seoInput(Obj)
{
    Obj.val(function(i, v) {return v.replace(/\s/ig,'-');});
    Obj.val(function(i, v) {return v.replace(/[^a-z0-9\-]/i,'');});
}
</script>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">Welcome to my portfolio</h1>
<p class="text-center">Here are a few of the projects I have worked on over the years</p>

<h2>Latest Posts {% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'portfolio:manage' %}"><i class="fa fa-plus" aria-hidden="true"></i> New Post</a><br>
{% endif %}</h2>
<hr>
{% for post in posts.all %}
<br><br>
<h3><a href="{% url 'portfolio:portfolio_post' post.pub_date|date:'Y' post.pub_date|date:'m' post.pub_date|date:'d' post.seotitle %}">{{ post.title }}</a></h3>
<def><i class="fa fa-clock-o" aria-hidden="true"></i> {{post.pub_date_pretty}}</def>
{% if post.image %}<p><img src='{{post.image.url}}' alt='' style='max-height:200px' class='img-fluid d-block'></p>{% endif %}
<p>{{ post.body|truncatewords_html:80|safe }}</p>
{% endfor %}
{% endblock %}

portfolio/templates/portfolio/portfolio_post.html
{% extends 'base.html' %}
{% load static %}
{% block headscript %}
<meta property="fb:app_id" content="1367180106713752" />
<meta property="og:url"                content='http://aristia.net/portfolio/{{ post.pub_date|date:"Y/m/d"}}/{{ post.seotitle }}/' />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="{{post.title}}" />
<meta property="og:description"        content="{{post.body|safe|truncatewords_html:8}}" />
{% if post.image %}
<meta property="og:image"              content="http://aristia.net{{post.image.url}}" />
{% else %}
<meta property="og:image"              content="http://aristia.net{% static 'sitepages/img/header.jpg' %}" />
{% endif %}
{% endblock %}
{% block afterbody %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endblock %}
{% block content %}
<div class="page-header">
<h1>{{post.title}}</h1>
</div>
<def><i class="fa fa-clock-o" aria-hidden="true"></i> {{post.pub_date_pretty}}</def> {% if user.is_authenticated %}
<a href="{% url 'portfolio:manage' post.id %}" title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
{% endif %}
{% if post.image %}<p><img src='{{post.image.url}}' alt='' style='max-height:400px' class='img-fluid center-block'></p>{% endif %}
<p>{{post.body|safe}}</p>
<div class="fb-comments" data-href='http://aristia.net/portfolio/{{ post.pub_date|date:"Y/m/d"}}/{{ post.seotitle }}/' data-numposts="5" data-width="100%"></div>
{% comment %}
	<div id="disqus_thread"></div>
	<script>

	var disqus_config = function () {
	this.page.identifier = 'post-{{ post.id }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	};

	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	s.src = 'https://aristiasportfolio.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endcomment %}
	
{% endblock %}