blog/urls.py
from django.conf.urls import static
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='blog'

urlpatterns = [
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<seotitle>[\d\w\-]+)/$', views.blog_post, name='blog_post'), 
    url(r'^manage(?:/(?P<pk>[\d\w\-]+))?', views.manage, name='manage'),
    url('', views.home, name='home'),
]

shows/urls.py
from django.urls import re_path as url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from . import views

app_name='shows'

urlpatterns = [
    url(r'^ajax/dl/$', views.dl, name='dl'),
    url(r'^ajax/dlm/$', views.dlm, name='dlm'),
    url(r'^manage(?:/(?P<seotitle>[\d\w\-]+))?', views.manage, name='manage'),
    url(r'^onbreak', views.onbreak, name='onbreak'),
    url(r'^movies/manage(?:/(?P<seotitle>[\d\w\-]+))?', views.managemovie, name='managemovie'),
    url(r'^movies', views.movies, name='movies'),
    url(r'^(?P<seotitle>[\d\w\-]+)$', views.series, name='series'),
    url('',views.home, name='home'),
]
    

shows/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta, datetime, date

dt_1000 = timezone.make_aware(datetime(1000,1,1,0,0,0))

# Create your models here.
class Series(models.Model):
    title = models.CharField(max_length=200)
    seotitle = models.CharField(max_length=200,unique=True)
    period = models.CharField(max_length=200,null=True,blank=True)
    firstaired = models.DateTimeField()
    lastdue = models.DateTimeField()
    lastepi = models.CharField(max_length=10)
    overview = models.TextField(null=True,blank=True)
    rssfeedid = models.IntegerField(unique=True)
    audCHOICES = (('', 'All',), ('Mat', 'Mat',), ('Stella', 'Stella',))
    audience = models.CharField(max_length=200,null=True,blank=True,choices=audCHOICES,default='')
    imdb = models.CharField(max_length=200,null=True,blank=True)
    banner = models.ImageField(upload_to='shows/bart/',null=True,blank=True)
    thumb = models.ImageField(upload_to='shows/tart/',null=True,blank=True)
    lastlookup = models.DateTimeField()
    tvdbid = models.IntegerField()

    def __str__(self):
        return self.title.replace("\\'","\'")

    def clean_title(self):
        c=self.title
        replace = [" ","\\'",":","."]
        for i in replace:
            c=c.replace(i,'')
        return c

    def audience_letter(self):
        return self.audience[0]

    def tvdblink(self):
        return "http://www.thetvdb.com/?tab=series&id={0}&lid=7".format(self.tvdbid)

    def imdblink(self):
        return "http://www.imdb.com/title/{0}/".format(self.imdb)

    def rsslink(self):
        return "http://showrss.info/browse/{0}".format(self.rssfeedid)

    def banner_img(self):
        return "/shows/img/bart/{0}.jpg".format(self.tvdbid)

    def readmorelink(self):
        if len(self.overview.split()) > 80:
            return "<a id='readmore'>Read More</a>"
        else:
            return ""

    def title_pretty(self):
        return self.title.replace("\\'","\'")

    def firstaired_pretty(self):
        return self.firstaired.strftime('%M')

    def audience_icon_letter(self):
        if self.audience:
            return "<span class='" + self.audience.lower() + "'>" + self.audience[0] + "</span> "
        else:
            return ""

    def audience_icon(self):
        if self.audience:
            return "<i class='fa fa-user-circle " + self.audience.lower() + "' aria-hidden='true'></i> "
        else:
            return ""
        
    class Meta:
        db_table = 'shows_series'

class Episode(models.Model):
    series = models.ForeignKey(Series, related_name='sid', on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    season = models.IntegerField()
    episode = models.IntegerField()
    serid = models.IntegerField()
    seaid = models.IntegerField()
    epiid = models.IntegerField()
    rssid = models.IntegerField(null=True,blank=True)
    rssdate = models.DateTimeField(null=True,blank=True)
    desc = models.TextField()
    date_added = models.DateTimeField()
    due = models.DateTimeField()
    link = models.TextField()
    downloaded = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return  '{0} S:{1} E{2} Due {3}'.format(self.title.replace("\\'","\'"),self.season,self.episode,self.due)

    def title_pretty(self):
        return self.title.replace("\\'","\'")

    def tvdblink(self):
        return "http://www.thetvdb.com/?tab=episode&seriesid={0}&seasonid={1}&id={2}&lid=7".format(self.serid,self.seaid,self.epiid)

    def tvdbslink(self):
        return "http://www.thetvdb.com/?tab=season&seriesid={0}&seasonid={1}&lid=7".format(self.serid,self.seaid)

    def imdblink(self):
        return "http://www.imdb.com/title/{0}/episodes?season={1}".format(self.rsskey.imdb,self.season)

    def due_plus(self):
        return self.due + timedelta(days=1)

    def thumb(self):
        return "/shows/img/fart/{0}.jpg".format(self.serid)

    def banner(self):
        return "/shows/img/bart/{0}.jpg".format(self.serid)

    def due_pretty(self):
        dayadded = self.due + timedelta(days=1)
        if timezone.now().year == dayadded.year:
            return dayadded.strftime('%A %b %e')
        else:
            return dayadded.strftime('%b %e %Y')

    def date_added_pretty(self):
        return self.date_added.strftime('%b %e %Y')

    def downloaded_pretty(self):
        if self.downloaded is not None and self.downloaded > dt_1000:
            return self.downloaded.strftime('%b %e %Y')
        else:
            return 'No'

    def rssdate_pretty(self):
        return self.rssdate.strftime('%b %e %Y')

    def episode_detail(self):
        if self.season == 0:
            return 'Special'
        else:
            return 'S:{0} E:{1}'.format(self.season,self.episode)

    class Meta:
        ordering = ('-season','-episode')
        db_table = 'shows_episodes'


class Media(models.Model):
    title = models.CharField(max_length=200)
    seotitle = models.CharField(max_length=200,unique=True)
    overview = models.TextField(null=True,blank=True)
    turl = models.URLField()
    datestr = models.DateTimeField()
    episode = models.IntegerField(default=0)
    certCHOICES = (
        ("U","U"),
        ("PG","PG"),
        ("12","12"),
        ("12A","12A"),
        ("PG-13","PG-13"),
        ("15","15"),
        ("18","18")
    )
    cert = models.CharField(max_length=200,choices=certCHOICES,default='18')
    typCHOICES = (('movie', 'Movie',), ('tv', 'TV',), ('book', 'Book',))
    typ = models.CharField(max_length=100,choices=typCHOICES,default='movie')
    gotCHOICES = ((0,'No'),(1,'Yes'))
    got = models.IntegerField(default=0,choices=gotCHOICES)
    banner = models.ImageField(upload_to='shows/mart/',null=True,blank=True)

    def __str__(self):
        return self.title

    def datestr_pretty(self):
        return self.datestr.strftime('%b %e %Y')

    def poster(self):
        return "/shows/img/mart/{0}.jpg".format(self.id)

    def certimg(self):
        return "shows/img/pegi/{0}.png".format(self.cert.lower())

    class Meta:
        db_table = 'shows_movies'

shows/views.py
from django.core.cache import cache
from django.views.decorators.cache import never_cache
from django.shortcuts import render, get_object_or_404, redirect
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.decorators import permission_required, login_required
from django.http import JsonResponse
from django.db.models import Q
from .models import Episode, Series, Media
from django.db.models import Count
from .forms import SeriesForm, MediaForm
from datetime import date, datetime, time, timedelta
from time import mktime
from pytvdbapi import api
import feedparser
import re
import urllib.request
import os

'''
TODO:
---
Styling - try for flex to share space with columns
permissions
hover show display details in popup (including last seen episode and last inserted episode)
button to hide all shows not your own/universal
display relative weekday headers instead of the day name?
page for all shows in case they aren't on any page (this happens if they were ticked today and thus not in this week's list but also not on a break) and order by status (active/on break/inactive).
'''

cache.clear()
dt_1000 = timezone.make_aware(datetime(1000,1,1,0,0,0))

#@permission_required('shows.series.can_edit')
@login_required
@never_cache
def home(request):
    today = date.today()
    dt_today = timezone.make_aware(datetime.combine(today, time.min))
    dt_yesterday = timezone.make_aware(datetime.combine(today - timedelta(days=1), time.min))
    dt_tomorrow = timezone.make_aware(datetime.combine(today + timedelta(days=1), time.min))
    dt1 = timezone.make_aware(datetime.combine(today + timedelta(days=6), time.max))
    dt2 = timezone.make_aware(datetime.combine(today - timedelta(days=14), time.min))
    err=''
    # UPDATE EPISODES #
    try:
        tvdb()
    except:
        err = 'TVDB not available to update shows.'

    # CREATE DICTIONARIES #
    weekdays = [dt_yesterday + timedelta(days=x+1) for x in range((dt1-dt_yesterday).days)]
    thisweek = Episode.objects.filter(due__range=(dt_yesterday, dt1)).filter(downloaded__lte=dt_1000).exclude(season=0).order_by('-due','title')
    errors = Episode.objects.filter(due__lt=dt_yesterday).filter(due__gt=dt2).filter(downloaded__lte=dt_1000).exclude(season=0).order_by('-due','title')
    dltoday = Episode.objects.filter(downloaded__range=(dt_today,dt_tomorrow))
    dltodaytext = ''

    if dltoday:
        dltodaytext = '<b>Downloaded Today</b><br>'
    for dlt in dltoday:
        dltodaytext += str(dlt.title_pretty()) + '&nbsp;' + str(dlt.episode_detail()) + '<br>'

    # GET LINKS FROM SHOWSRSS #
    for epi in errors:
        rsslink(epi)
    for epi1 in thisweek:
        rsslink(epi1)

    return render(request,'shows/home.html',{
        'weekdays': weekdays,
        'thisweek': thisweek,
        'dltoday': dltodaytext,
        'errors': errors,
        'err': err
        })

@login_required
def series(request,seotitle):
    today = date.today()
    dt_today = timezone.make_aware(datetime.combine(today, time.min))
    show = Series.objects.get(seotitle=seotitle)

    seasonDict = {}
    for epi in show.sid.all():
        if epi.season > 0:
            if epi.downloaded is not None and epi.downloaded <= dt_1000:
                rsslink(epi)
            if epi.season not in seasonDict:
                seasonDict[epi.season] = {}
            seasonDict[epi.season][epi.episode] = {
            'episod':epi.id,
            'due':epi.due_pretty,
            'downloaded':epi.downloaded_pretty,
            'desc':epi.desc,
            'tvdb':epi.tvdblink,
            'tvdbs':epi.tvdbslink,
            'link':epi.link
            }
            if epi.due > dt_today:
                seasonDict[epi.season][epi.episode]['future'] = ' faded'
            else:
                seasonDict[epi.season][epi.episode]['future'] = ''
    return render(request,'shows/show_detail.html',{'show':show,'seasons':seasonDict})

@login_required
def manage(request,seotitle):
    if seotitle:
        show = get_object_or_404(Series,seotitle=seotitle)
    else:
        show = Series()

    if request.method == 'POST':
        form = SeriesForm(request.POST,instance=show,label_suffix='')
        if seotitle is not None and 'deleteshow' in request.POST:
            try:
                module_dir = os.path.dirname(__file__)  # get current directory
                os.remove(os.path.join(module_dir, os.path.normpath('static/shows/img/bart/{0}.jpg').format(show.tvdbid)))
                os.remove(os.path.join(module_dir, os.path.normpath('static/shows/img/fart/{0}.jpg').format(show.tvdbid)))
            except:
                error = 'could not delete file'
            Episode.objects.filter(series=show).delete()
            show.delete()
            return redirect('shows:home')
        if form.is_valid():
            #self.cleaned_data - not needed in modelforms
            obj = form.save(commit=False)
            obj.lastlookup = dt_1000
            obj.save()

            if(seotitle is None):
                tvdb(obj.id)
            seotitle = obj.seotitle
            if 'save' in request.POST:
                return redirect('shows:series', seotitle=seotitle)
    else:
        form = SeriesForm(instance=show,label_suffix='')
    if(seotitle):# Here we are editing
        data = {
        'head':"Editing " + seotitle,
        'urlstuff': seotitle
        }
    else:# Here we are adding
        data = {
        'head':"Add New Show",
        'urlstuff': ''
        }

    return render(request,'shows/manage.html',{'data':data,'form':form})

@never_cache
def onbreak(request):
    #series where no episodes this week
    today = date.today()
    dt_today = timezone.make_aware(datetime.combine(today, time.min))
    dt_yesterday = timezone.make_aware(datetime.combine(today - timedelta(days=1), time.min))
    dt1 = timezone.make_aware(datetime.combine(today + timedelta(days=6), time.max))
    thisweek = Episode.objects.filter(due__range=(dt_yesterday, dt1)).exclude(series_id=None).exclude(season=0).order_by('-due','title').select_related('series').values_list('series_id',flat=True)

    # series with no episodes this week
    onbreakq = Episode.objects.exclude(series_id__in=thisweek).exclude(due__lt=dt_today).exclude(season=0).order_by('due','title').select_related('series')
    onbreak = {}
    for ob in onbreakq:
        if ob.series.seotitle not in onbreak:
            onbreak[ob.series.seotitle] = {
            'title':ob.series.title_pretty,
            'overview':ob.series.overview,
            'audience':ob.series.audience,
            'banner':ob.series.banner_img,
            'rsslink':ob.series.rsslink,
            'imdblink':ob.series.imdblink,
            'tvdblink':ob.series.tvdblink,
            'due':ob.due_pretty,
            'detail':ob.episode_detail
            }

    upcomingepi = Episode.objects.filter(due__gte=dt_today).exclude(series_id=None).values_list('series_id',flat=True)
    print(upcomingepi)

    inactive = Series.objects.exclude(pk__in=upcomingepi).extra(select={'firstair': 'MONTH(firstaired)'},order_by=['firstair'])
    return render(request,'shows/onbreak.html',{'onbreak':onbreak,'inactive':inactive})


def managemovie(request,seotitle=''):
    if seotitle:
        media = get_object_or_404(Media, seotitle=seotitle)
    elif seotitle is None:
        media = Media()

    if request.method == 'POST':
        form = MediaForm(request.POST, request.FILES,instance=media,label_suffix='')

        # DELETE THE ENTRY
        if seotitle is not None and 'deletemovie' in request.POST and media.banner is not None:
            try:
                os.remove(settings.BASE_DIR + os.path.normpath(media.banner.url))
            except:
                error = 'could not delete file'
            media.delete()
            return redirect('shows:movies')

        # SAVE THE ENTRY
        datestring = datetime.strptime(request.POST['datestr'], '%d/%m/%Y')
        if form.is_valid():
            obj = form.save(commit=False)
            obj.datestr = timezone.make_aware(datetime.combine(datestring, time.min))
            obj.save()
        seotitle = media.seotitle
        if 'save' in request.POST:
            return redirect('shows:movies')
    else:
        form = MediaForm(instance=media,label_suffix='')
    return render(request,'shows/managemovie.html',{'data':media,'form':form})

def movies(request):
    today = date.today()
    dt_today = timezone.make_aware(datetime.combine(today, time.min))
    movies = Media.objects.order_by('got','datestr')
    released = {}
    upcoming = {}
    for movie in movies:
        movie.typ = movie.typ or 'movie'
        data = {
        'title':movie.title,
        'seotitle':movie.seotitle,
        'date':movie.datestr_pretty,
        'typ':movie.typ,
        'overview':movie.overview,
        'turl':movie.turl,
        'got':movie.got,
        'banner':movie.banner,
        'id':movie.id
        }
        if movie.got == 1:
            data['fade'] = ' faded'
        else:
            data['fade'] = ''
        if movie.cert is not None and movie.cert != '':
            data['certimg']=movie.certimg
        if movie.datestr > dt_today:
            if movie.typ.lower() not in upcoming:
                upcoming[movie.typ.lower()] = []
            upcoming[movie.typ.lower()].append(data)
        else:
            if movie.typ.lower() not in released:
                released[movie.typ.lower()] = []
            released[movie.typ.lower()].append(data)

    return render(request,'shows/movies.html',{'released':released,'upcoming':upcoming})
'''
UTILIY METHODS
'''

def rsslink(epis):
    epi = Episode.objects.get(pk=epis.pk)
    sea=str(epi.season).zfill(2)
    ep=str(epi.episode).zfill(2)
    thislink = epi.link
    today = date.today()
    thisdate = timezone.make_aware(datetime.combine(today, time.min))

shows/templates/shows/default.html
{% extends 'base.html' %}
{% load static %}
{% block headscript %}
<meta http-equiv="Cache-control" content="no-cache">
{% endblock %}
{% block styles %}
<link rel="stylesheet" href="{% static 'shows/css/style.css' %}">
{% endblock %}

shows/templates/shows/manage.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'shows/css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/css/bootstrap-datepicker.min.css">
{% endblock %}
{% block content %}
<br><h1>{{ data.head|title }}</h1>
{% if error %}
{{ error}}
{% endif %}
<br>
{% if data.urlstuff %}
<form action="{% url 'shows:manage' data.urlstuff %}" method="post">
{% else %}
<form action="{% url 'shows:manage' %}" method="post">
{% endif %}
{% csrf_token %}

{% for field in form %}
    {% if field.name == 'audience' %}
        <h4><i class="fa fa-{{ field.label }} fa-fw" aria-hidden="true"></i> {{ field.help_text }}</h4>
        <div class="form-inline">
        {% for choice in field %}
            <label class="custom-control custom-radio {{ choice.choice_label|lower }}">
                {{ choice.tag }}            
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">{{ choice.choice_label }}</span>
            </label>
        {% endfor %}
        </div>
    {% else %}
        <div class="input-group">
            <label for="{{ field.auto_id }}" class="input-group-addon" title="{{ field.help_text }}"><i class="fa fa-{{ field.label }} fa-fw" aria-hidden="true"></i></label>
            {{ field }}
        </div>
    {% endif %}
<br>
{% endfor %}
<br><br><button class="btn btn-primary" type="submit" name="savecontinue"><i class="fa fa-floppy-o" aria-hidden="true"></i> {% if data.urlstuff %}Save{% else %}Add{% endif %} and continue editing</button> <button class="btn btn-primary" type="submit" name="save"><i class="fa fa-floppy-o" aria-hidden="true"></i> {% if data.urlstuff %}Save{% else %}Add{% endif %}</button>
{% if data.urlstuff %}<button class="btn btn-danger" type="submit" name="deleteshow"><i class="fa fa-times" aria-hidden="true"></i> Delete</button>
{% endif %}
</form>
{% endblock %}
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/js/bootstrap-datepicker.min.js"></script>
<script>
$('#id_seotitle').on("keyup",function(){seoInput($(this))});

$('#id_seotitle').on("focus",function(){
    if($(this).val().length < 1){
        $(this).val=$('#id_title').val().toLowerCase();
        $(this).val(function(i, v) {return $('#id_title').val().toLowerCase();});
        seoInput($(this))
    }
});
function seoInput(Obj)
{
    Obj.val(function(i, v) {return v.replace(/\s/ig,'-');});
    Obj.val(function(i, v) {return v.replace(/[^a-z0-9\-]/i,'');});
}
</script>
{% endblock %}

shows/templates/shows/managemovie.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'shows/css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
{% endblock %}
{% block content %}
<br><h1>{% if data.title %}Editing {{ data.title|title }}{% else %}Add a new media release{% endif %}</h1>
{% if form.errors or error %}
<div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Error:<br>{{ form.errors }}
{% if error %}<br>{{ error }}{% endif %}</div>
{% endif %}
<br>
{% if data.seotitle %}
<form action="{% url 'shows:managemovie' data.seotitle %}" method="post" enctype="multipart/form-data">
{% else %}
<form action="{% url 'shows:managemovie' %}" method="post" enctype="multipart/form-data">
{% endif %}
{% csrf_token %}
{% for field in form %}
    {% if field.name == 'typ' %}
        <h4><i class="fa fa-{{ field.label }} fa-fw" aria-hidden="true"></i> {{ field.help_text }}</h4>
        <div class="form-inline">
        {% for choice in field %}
            <label class="custom-control custom-radio {{ choice.choice_label|lower }}">
                {{ choice.tag }}            
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">{{ choice.choice_label|safe }}</span>
            </label>
        {% endfor %}
        </div>
    {% else %}
        <div class="input-group">
            <label for="{{ field.auto_id }}" class="input-group-addon" title="{{ field.help_text }}"><i class="fa fa-{{ field.label }} fa-fw" aria-hidden="true"></i></label>
            {% if field.name == 'banner' and form.banner %}<span class="form-control" style="display:inline">{% endif %}
            {{ field }}
            {% if field.name == 'banner' %}</span>{% endif %}
        </div>
    {% endif %}
<br>
{% endfor %}
<br><br>
<button class="btn btn-primary" type="submit" name="savecontinue"><i class="fa fa-floppy-o" aria-hidden="true"></i> {% if data.title %}Save{% else %}Add{% endif %} and continue editing</button> <button class="btn btn-primary" type="submit" name="save"><i class="fa fa-floppy-o" aria-hidden="true"></i> {% if data.title %}Save{% else %}Add{% endif %}</button>
{% if data.seotitle %}<button class="btn btn-danger" type="submit" name="deletemovie"><i class="fa fa-times" aria-hidden="true"></i> Delete</button>
{% endif %}

</form>
{% endblock %}
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.0/js/bootstrap-datepicker.min.js"></script>
<script>
$(document).ready(function(){
$('#id_datestr').datepicker({ 
    format: 'dd/mm/yyyy'
    });
});
$('#id_seotitle').on("keyup",function(){seoInput($(this))});

$('#id_seotitle').on("focus",function(){
    if($(this).val().length < 1){
        $(this).val=$('#id_title').val().toLowerCase();
        $(this).val(function(i, v) {return $('#id_title').val().toLowerCase();});
        seoInput($(this))
    }
});
function seoInput(Obj)
{
    Obj.val(function(i, v) {return v.replace(/\s/ig,'-');});
    Obj.val(function(i, v) {return v.replace(/[^a-z0-9\-]/i,'');});
}
</script>
{% endblock %}

shows/templates/shows/show_detail.html
{% extends 'shows/default.html' %}
{% load static %}

{% block content %}
<h1>{{ show.title }}</h1>
<img src="{% static show.banner_img %}" alt="" class='center-block main-banner'>
<p><span id="ov"><a href="{% url 'shows:manage' show.seotitle %}" title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a> <a href="{{ show.rsslink }}" target="_blank" title="ShowRSS"><i class="fa fa-rss-square" aria-hidden="true"></i></a> <a href="{{ show.tvdblink }}" target="_blank" title="TheTVDB"><i class="fa fa-tv" aria-hidden="true"></i></a> <a href="{{ show.imdblink }}" target="_blank" title="IMDB"><i class="fa fa-imdb" aria-hidden="true"></i></a> {{ show.overview|safe|linebreaks }}</span></p>
<hr>
{% for k,season in seasons.items %}
<ul class="episodes">
    <li>
        <h2>Season {{ k }}</h2>
        <ul>
            {% for k2,episode in season.items %}
            <li class="{% cycle 'odd' 'even' %}{{ episode.future }}"><i class="fa fa-info-circle" aria-hidden="true" title="{{ episode.desc }}" data-toggle="tooltip" ></i> {{ k2 }}: <b>Due:</b> {{ episode.due }}<span id="dlinfo{{ episode.episod }}">{% if episode.downloaded != 'No' %}, <b>Downloaded:</b> {{ episode.downloaded }}{% elif episode.link %} <a data-dllink="{{ episode.link }}" id="{{ episode.episod }}" class="dl-link"><i class="fa fa-download" aria-hidden="true"></i></a>{% elif episode.future == '' and episode.downloaded != 'No' %} <a data-dllink="1" id="{{ episode.episod }}" class="dl-link"><i class="fa fa-check" aria-hidden="true"></i></a>{% endif %}</span> </li>
            {% endfor %}
        </ul>
    </li>
</ul>
{% endfor %}
<iframe id="dl_capture"></iframe>
{% endblock %}
{% block script %}
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
        placement : 'top'
    });
});
$("a.dl-link").click(function () {
    var dllink = this.dataset.dllink;
    var clickedObj = this.id

    $.ajax({
        url: '{% url "shows:dl" %}',
        data: {
            'epi': this.id,
            'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        type: 'POST',
        dateType: 'json',
        success: function (data) {                
            if( dllink != 1 ){ $('#dl_capture').attr('src',dllink) }
            if( $('#dlinfo'+data.id).length ) { $('#dlinfo'+data.id).html(data.downloaded) }
            if (data) {
                console.log(data);
            }
        }
    });
});
</script>
{% endblock %}